version: '2.2'
services:
  node_server:
    # image: prendi/cellar_project:v1.0.0
    image: infuriatedleek/react_node:v1.0.1
    ports:
     - "4000:80"
    environment:
     - MYSQL_USER=root
     - MYSQL_PASSWORD=
     - MYSQL_DATABASE=xkcd
     - MYSQL_HOST=mysql
    volumes:
     - ./:/node_server
    depends_on:
     - mysql
  mysql:
    image: mysql:5.7
    ports:
     - "3306:3306"
    volumes:
     - ./dev_setup/:/docker-entrypoint-initdb.d
    environment:
     - MYSQL_ALLOW_EMPTY_PASSWORD=yes
