version: '2.2'
services:
  node_server:
    image: infuriatedleek/react_node:v1.0.2
    ports:
     - "80:4000"
    environment:
     - MYSQL_USER=root
     - MYSQL_PASSWORD=
     - MYSQL_DATABASE=xkcd
     - MYSQL_HOST=mysql
    # volumes:
    #  - ./:/node_server
    depends_on:
     - mysql
  mysql:
    image: mysql:5.7
    ports:
     - "3306:3306"
    volumes:
     - ./dev_setup/:/docker-entrypoint-initdb.d
    environment:
     - MYSQL_ALLOW_EMPTY_PASSWORD=yes
